### ISSUE TITLE
新加入的付款功能/延迟请求/地址id啥的希望补全下文档

### ISSUE THREAD

**Issue by LI8511** [Yx1aoq1/jdms#10]
有个问题，假设点击开抢，然后时间未到，能一直抢么？我看弹窗弹一段时间就不会弹出了;也就是说，我不能一直点一个开枪进行挂机操作吗？wang

**Comment by LI8511** [comment]
望作者大大求解，star已点~💗

**Comment by Yx1aoq1** [comment]
文档已补充：[使用说明](https://github.com/Yx1aoq1/jdms/blob/master/doc/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)

时间未到的时候点击开抢，会在后台执行定时器，然后判断时间是不是到了，到了才会发送提交订单请求。因为时间还没有到的时候感觉没有什么必要输出的信息，所有基本上没有弹窗了。到设置的抢购时间的前十分钟会在控制台输出一个倒计时的log，到真正开始抢的时候才会再弹弹窗。
只要你看到操作按钮是“停止”，以及图标再转圈圈就是有在后台执行。不过也不是很建议很早之前就开始挂机，因为登录可能会过期。
