### ISSUE TITLE
Win下的软件还需要其他配置么？试了几个整点秒杀的商品，发现都没有提交订单

### ISSUE THREAD

**Issue by openxbmc** [Yx1aoq1/jdms#7]
RT,直接下载了Win的可执行软件，配置账号和商品，设置到点抢购，但没有反馈，时间过了后，商品其实还可以买，但软件没有下单。

**Comment by Yx1aoq1** [comment]
预约的商品要自己提前加到购物车里，然后点开抢，到点的时候会提交订单。本质是到点请求了京东的购物车结算的接口，所以要确认好购物车里的商品有你预约的那个，以及没有其他可以买的商品，不然会一起提交

**Comment by openxbmc** [comment]
> 预约的商品要自己提前加到购物车里，然后点开抢，到点的时候会提交订单。本质是到点请求了京东的购物车结算的接口，所以要确认好购物车里的商品有你预约的那个，以及没有其他可以买的商品，不然会一起提交

OK，我试试 不过茅台是不行了，茅台不支持加入购物车的操作
